### ISSUE TITLE
TypeError when multi-thread inference using tensor_parallel

### ISSUE THREAD

**Issue by liulhdarks** [BlackSamorez/tensor_parallel#89]
When inference model with multiple thread, it will throw TypeError
```
  File "/data/miniconda3/envs/python39/lib/python3.9/concurrent/futures/_base.py", line 446, in result
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
    return self.__get_result()
  File "/data/miniconda3/envs/python39/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/data/miniconda3/envs/python39/lib/python3.9/concurrent/futures/thread.py", line 58, in run
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
    result = self.fn(*self.args, **self.kwargs)
  File "/data/workspace/code/generate-demo/inference/starcoder_multithread.py", line 174, in gen_streamer
    outputs = model.generate(input_ids=input_ids, streamer=streamer, max_new_tokens=256, top_p=0.8, early_stopping=True, temperature=0.8, repetition_penalty=1.0)
  File "/data/miniconda3/envs/python39/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/miniconda3/envs/python39/lib/python3.9/site-packages/transformers/generation/utils.py", line 1437, in generate
    return self.greedy_search(
  File "/data/miniconda3/envs/python39/lib/python3.9/site-packages/transformers/generation/utils.py", line 2248, in greedy_search
    outputs = self(
  File "/data/miniconda3/envs/python39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/miniconda3/envs/python39/lib/python3.9/site-packages/tensor_parallel/pretrained_model.py", line 82, in forward
    return self.wrapped_model(*args, **kwargs)
  File "/data/miniconda3/envs/python39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/miniconda3/envs/python39/lib/python3.9/site-packages/tensor_parallel/tensor_parallel.py", line 129, in forward
    return parallel_apply(self.module_shards, inputs, kwargs_tup, self.devices)[self.output_device_index]
  File "/data/miniconda3/envs/python39/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/data/miniconda3/envs/python39/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
start generate: 10
    raise exception
TypeError: Caught TypeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/data/miniconda3/envs/python39/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/data/miniconda3/envs/python39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
 ...........
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by BlackSamorez** [comment]
Hi! Mutli-thread inference isn't supported at this point. See #86
